export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const REMOVE_BOOKMARKS = 'REMOVE_BOOKMARKS';
export const REMOVE_BOOKMARK = 'REMOVE_BOOKMARK';
export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const HIDE_BOOKMARK = 'HIDE_BOOKMARK';
export const REMOVE_HIDDEN = 'REMOVE_HIDDEN';
