export const GET_COMICS_REQUEST = 'GET_COMICS_REQUEST';
export const GET_COMICS_SUCCESS = 'GET_COMICS_SUCCESS';
export const GET_COMIC_SUCCESS = 'GET_COMIC_SUCCESS';
export const GET_COMICS_FAILURE = 'GET_COMICS_FAILURE';
export const CLEAN_COMICS = 'CLEAN_COMICS';
