export const GET_STORIES_REQUEST = 'GET_STORIES_REQUEST';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';
export const CLEAN_STORIES = 'CLEAN_STORIES';
